<?php
echo '<table id="parkinfotable">';
foreach ($results as $column) {
    echo '<tr>';
    echo '<td></td>';
    echo '<td></td>';
    echo '</tr>';
}
echo '</table>';
?>

<table id="parkinfotable">
  <tr>
    <td>ID:</td>
    <td>1</td>
  </tr>
  <tr>
  	<td>Park Code:</td>
  	<td>D0228</td>
  </tr>
  <tr>
  	<td>Park Name:</td>
  	<td>7th brigade park</td>
  </tr>
  <tr>
  	<td>Street:</td>
  	<td>Hamilton rd</td>
  </tr>
  <tr>
  	<td>Suburb:</td>
  	<td>Chermside</td>
  </tr>
  <tr>
  	<td>Node ID:</td>
  	<td>16381</td>
  </tr>
  <tr>
  	<td>Dog Park Name:</td>
  	<td>REINHOLD CRES DOG OFF LEASH AREA</td>
  </tr>
  <tr>
  	<td>Dog Park Area:</td>
  	<td>10000M SQ</td>
  </tr>
  <tr>
  	<td>Latitude:</td>
  	<td>-23.234234234</td>
  </tr>
  <tr>
  	<td>Longitude:</td>
  	<td>145.12315325</td>
  </tr>
</table>